name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup RDP
        run: |
          curl -s https://raw.githubusercontent.com/CYB3RKING/RDP/main/setup.sh | bash