
name: Install RDP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download script
        run: curl -s https://raw.githubusercontent.com/CYB3RKING/RDP/main/setup.sh | bash
    